# Generated by Django 3.1 on 2021-04-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20210311_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dob',
            field=models.DateField(default='yyyy-MM-dd'),
        ),
        migrations.AlterField(
            model_name='member',
            name='registration_date',
            field=models.DateField(default='yyyy-MM-dd', verbose_name='Registration Date'),
        ),
    ]
