# Generated by Django 3.1 on 2021-03-05 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='notification',
        ),
    ]
